
services:
  nginx:
    image: nginx:alpine
    container_name: press_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./achrafrachid.salon.crt:/etc/nginx/ssl/achrafrachid.salon.crt:ro
      - ./achrafrachid.salon.key:/etc/nginx/ssl/achrafrachid.salon.key:ro

    depends_on:
      - nextjs
    restart: unless-stopped

  nextjs:
    build: .
    container_name: press_nextjs
    expose:
      - "3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass123
      MYSQL_DATABASE: ligne_press_db
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:9
    container_name: press_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: ligne_press_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
